#!/usr/bin/env python3
"""
将生成的图嵌入到 Manuscript_Final_MC-SIRC.docx 与 SI_Final.docx
- 替换正文里的 [Insert Figure X...] 占位符为实际图片
- 改写更详细的 captions
- 在 SI 末尾追加 4 张 SI 图 + captions
- 在正文里加 SI 图引用
"""
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

import docx
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pathlib import Path
import shutil

ROOT = Path('D:/shanxi')
FIG_DIR = ROOT / 'output' / 'figures'
MS_DOCX = ROOT / 'paper' / 'Manuscript_Final_MC-SIRC.docx'
SI_DOCX = ROOT / 'paper' / 'SI_Final.docx'

# 备份当前
shutil.copy2(MS_DOCX, MS_DOCX.with_suffix('.docx.fig_bak'))
shutil.copy2(SI_DOCX, SI_DOCX.with_suffix('.docx.fig_bak'))
print("备份: *.docx.fig_bak")

# ─────────────── 详细 captions ───────────────
CAPTIONS = {
    'fig1': ("Figure 1. Geographic location of the Nanchuan River Basin and the MC-SIRC analytical framework. "
             "(a) Watershed boundary (1,438 km²) showing the four control units (CU1–CU4), six townships, "
             "river network, distribution of 100 georeferenced point sources, and the outlet automated water-quality "
             "monitoring station (red triangle). (b) Five-stage progressive analytical pipeline: emission inventory → "
             "river-entry estimation → Bayesian MAP+MCMC coefficient optimization → Monte Carlo uncertainty "
             "quantification → spatial distance-decay modeling. The outlet monitored load (right) provides the "
             "top-down constraint that closes the inventory-monitoring chain."),

    'fig2': ("Figure 2. Bayesian optimization and uncertainty analysis under Setup A. "
             "(a) MAP correction-factor heatmap across nine source categories and four pollutants; values approaching "
             "the lower bound 0.10 indicate strong evidence of upstream-coefficient overestimation. "
             "(b) MCMC posterior mean ± 95% credible interval for the five highest-contribution sources across pollutants; "
             "tightly bounded distributions (e.g., large livestock TP, mean = 0.115) indicate strong data constraint, "
             "while wide intervals indicate poor identifiability. "
             "(c) Top 20 of 34 source-pollutant pairs ranked by z-score (|MAP − μ_prior|/σ_prior); colors denote "
             "reliability ratings: A (z>2, data-driven anomaly; n=4), B (1<z≤2, substantial correction; n=5), "
             "C (z≤1, prior-influenced; n=25). "
             "(d) Cross-scenario prior sensitivity for COD (solid) and TP (dashed) for five key sources; "
             "TP large-livestock factor remains at 0.10 across all five priors, confirming a data-driven anomaly, "
             "whereas under S1 (μ=0.5) COD large-livestock and TP industrial/centralized factors move modestly "
             "off the boundary."),

    'fig3': ("Figure 3. Monte Carlo uncertainty propagation (10,000 iterations) compared with monitored loads and "
             "Bayesian MAP predictions. (a–d) River-entry load probability density distributions for COD, NH₃-N, TN, "
             "and TP, generated by sampling source-emission magnitudes (CV = 20%, normal) and river-entry coefficients "
             "(uniform [0.5, 1.5]× nominal). Red dashed line: monitored (S2-imputed) load; blue dashed line: Bayesian "
             "MAP prediction; gray shading: 5–95th percentile MC interval. The exceedance probability P(MC > monitored) "
             "and the MC-mean to monitored ratio are annotated. COD and TP show systematic over-estimation by "
             "uncorrected emissions (P > Mon. = 100%), motivating the Bayesian correction."),

    'fig4': ("Figure 4. Spatial attenuation model fit and the divergence between emission-share and effective-contribution-share. "
             "(a) Eight-month observed (circles, solid lines) vs model-predicted (squares, dashed lines) river loads "
             "for COD (blue) and TN (orange) under the calibrated 2-parameter exponential decay model "
             "(k_COD = 0.073 km⁻¹, R² = 0.81; k_TN = 0.18 km⁻¹, R² = 0.96). "
             "(b–d) Source-category emission share (light bars) vs effective contribution share at the outlet (dark bars) "
             "for COD, TN, and TP. The dramatic divergence — for example, large-livestock farming contributing 56.6% of "
             "COD emissions but only 10.3% of effective load, while the centralized facility rises from 6.8% emission "
             "to 26.8% effective — is the central finding of this study and motivates a differentiated control strategy."),

    'figS1': ("Figure S1. Monthly distribution of pollutant loads at the Zhongyang outlet station in 2022. "
              "(a–d) Monthly loads of COD, NH₃-N, TN, and TP (bars), with hourly-record count overlaid (line, right axis). "
              "Months with fewer than 400 hours (Aug–Nov) are shaded gray and were excluded from spatial-model "
              "calibration; the remaining eight months are used for the calibration in Figure 4(a) and Table 7."),

    'figS2': ("Figure S2. Full MCMC posterior summaries for all source-correction factors per pollutant. "
              "(a–d) For COD, NH₃-N, TN, and TP, each horizontal bar shows the 95% credible interval and the "
              "posterior mean (filled marker) for one source. Colors encode the reliability rating: "
              "Rating A (z > 2, red, data-driven), Rating B (1 < z ≤ 2, orange, substantial correction), and "
              "Rating C (z ≤ 1, gray, prior-influenced). Reference lines: prior mean (1.0, gray dotted) and "
              "lower bound (0.10, red dotted)."),

    'figS3': ("Figure S3. Leave-one-month-out cross-validation (LOMOCV) diagnostics for the spatial distance-decay model. "
              "(a–d) For each pollutant, bars show the relative error (predicted − observed)/observed when each "
              "calibration month is held out and the remaining months are refit. Red dashed lines mark the median "
              "absolute error reported in Table S15. TN (median |err| = 12.5%) shows accurate predictive performance "
              "consistent with R² = 0.96; COD is acceptable (41.6%); NH₃-N and TP show inadequate performance, "
              "consistent with the boundary-binding γ values reported in Table 7 and the inadequacy of simple "
              "exponential decay for biogeochemically active species."),

    'figS4': ("Figure S4. Three-stage source-allocation comparison: emission share → river-entry share → "
              "effective contribution at the outlet. (a–d) Stacked bars for COD, NH₃-N, TN, and TP, where the same "
              "source category appears in identical color across the three stages, allowing visual tracking of how "
              "each source's relative dominance changes as the analytical chain advances from upstream emission "
              "through the river-entry coefficient and the channel attenuation transformation. The largest "
              "rearrangements — large-livestock COD/TP losing share, centralized facility gaining share, "
              "TN dominated by centralized facility throughout — quantify the magnitude of the spatial-attenuation "
              "effect across the pollutant suite."),
}

# ─────────────── 处理 Manuscript ───────────────
print("\n" + "="*80)
print("更新 Manuscript_Final_MC-SIRC.docx")
print("="*80)

ms = docx.Document(str(MS_DOCX))

# 找 [Insert Figure X...] 占位符并替换
fig_paths = {
    1: FIG_DIR / 'figure1_watershed_framework' / 'figure1_watershed_framework.png',
    2: FIG_DIR / 'figure2_bayesian' / 'figure2_bayesian.png',
    3: FIG_DIR / 'figure3_monte_carlo' / 'figure3_monte_carlo.png',
    4: FIG_DIR / 'figure4_spatial_attenuation' / 'figure4_spatial_attenuation.png',
}
caption_keys = {1:'fig1', 2:'fig2', 3:'fig3', 4:'fig4'}

# 找到 caption 段落和占位段落
for fig_num in [1, 2, 3, 4]:
    cap_key = caption_keys[fig_num]
    new_caption = CAPTIONS[cap_key]

    # 找到 Figure N 的 caption 段
    cap_para_idx = None
    placeholder_idx = None
    for i, p in enumerate(ms.paragraphs):
        if p.text.strip().startswith(f'Figure {fig_num}.'):
            cap_para_idx = i
        if p.text.strip().startswith(f'[Insert Figure {fig_num}'):
            placeholder_idx = i
            break

    if cap_para_idx is None:
        print(f"  ✗ Figure {fig_num} caption not found")
        continue

    # 替换 caption 段文字
    cap_para = ms.paragraphs[cap_para_idx]
    runs = list(cap_para.runs)
    if runs:
        runs[0].text = new_caption
        for r in runs[1:]:
            r.text = ''
    print(f"  ✓ Figure {fig_num} caption updated")

    # 在占位符段插入图片 (替换占位符文字)
    if placeholder_idx is not None and fig_paths[fig_num].exists():
        ph_para = ms.paragraphs[placeholder_idx]
        # 清空占位符文字
        for r in ph_para.runs:
            r.text = ''
        # 将图插入到占位段（图放在 caption 之前: caption 后→占位前 顺序保持）
        # 实际上原顺序是: caption (Figure N. ...) → placeholder ([Insert Figure N: ...])
        # 改为: figure (实际 image 段) → caption
        # 但为了不打乱段落顺序, 直接把占位段的 run 替换成 image
        run = ph_para.add_run()
        # 适合 7-inch 单栏正文 (Word 默认页宽 ~6.5"); 单栏图用 6.5", 跨栏图用 6.5"
        run.add_picture(str(fig_paths[fig_num]), width=Inches(6.5))
        ph_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        print(f"  ✓ Figure {fig_num} image inserted")

ms.save(str(MS_DOCX))
print(f"  保存: {MS_DOCX}")

# ─────────────── 加 SI 图引用到正文 ───────────────
print("\n[Manuscript] 加入 SI 图引用")
ms = docx.Document(str(MS_DOCX))

# 引用替换
si_citations = [
    # Figure S2: in §3.2 MCMC paragraph
    ('full results Tables S16a–d',
     'full results Tables S16a–d, Figure S2'),
    # Figure S3: 在 §3.3 LOMOCV 句中
    ('Leave-one-month-out cross-validation (Table S15) confirmed',
     'Leave-one-month-out cross-validation (Table S15, Figure S3) confirmed'),
    ('Leave-one-month-out cross-validation (LOMOCV) assessed predictive accuracy',
     'Leave-one-month-out cross-validation (LOMOCV) assessed predictive accuracy (Figure S3)'),
]

for old, new in si_citations:
    for para in ms.paragraphs:
        full_text = ''.join(run.text for run in para.runs)
        if old in full_text and new not in full_text:
            new_text = full_text.replace(old, new)
            runs = list(para.runs)
            if runs:
                runs[0].text = new_text
                for r in runs[1:]: r.text = ''
            print(f"  ✓ '{old[:60]}...' → 加入 SI 图引用")
            break

# 在 §3.3 末尾加 Figure S4 引用
# 找到 "The point source distance distribution (Table S12)" 那段
for para in ms.paragraphs:
    full_text = ''.join(run.text for run in para.runs)
    if 'The point source distance distribution (Table S12)' in full_text and 'Figure S4' not in full_text:
        # 在该段末追加一句
        new_text = full_text.rstrip().rstrip('.') + ('. The full source-by-source allocation across emission, '
                                                      'river-entry, and effective contribution stages is presented in Figure S4.')
        runs = list(para.runs)
        if runs:
            runs[0].text = new_text
            for r in runs[1:]: r.text = ''
        print(f"  ✓ 加入 Figure S4 引用 (§3.3 段末)")
        break

ms.save(str(MS_DOCX))

# ─────────────── 处理 SI ───────────────
print("\n" + "="*80)
print("更新 SI_Final.docx — 追加 4 张 SI 图")
print("="*80)

si = docx.Document(str(SI_DOCX))

# 找 "Figure S1." caption（已有）的位置，把图替换/插入
si_fig_paths = {
    'S1': FIG_DIR / 'figureS1_monthly_loads' / 'figureS1_monthly_loads.png',
    'S2': FIG_DIR / 'figureS2_mcmc_posteriors' / 'figureS2_mcmc_posteriors.png',
    'S3': FIG_DIR / 'figureS3_lomocv' / 'figureS3_lomocv.png',
    'S4': FIG_DIR / 'figureS4_three_stage_allocation' / 'figureS4_three_stage_allocation.png',
}

# Figure S1 已经有 caption "Figure S1. Monthly pollutant load distribution" + 占位符 "[Insert monthly pollutant load distribution chart]"
for i, p in enumerate(si.paragraphs):
    if p.text.strip().startswith('Figure S1.'):
        # 替换 caption
        new_cap = CAPTIONS['figS1']
        runs = list(p.runs)
        if runs:
            runs[0].text = new_cap
            for r in runs[1:]: r.text = ''
        print(f"  ✓ Figure S1 caption updated")
    if p.text.strip().startswith('[Insert monthly pollutant'):
        # 插入图
        for r in p.runs:
            r.text = ''
        run = p.add_run()
        run.add_picture(str(si_fig_paths['S1']), width=Inches(6.5))
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        print(f"  ✓ Figure S1 image inserted")
        break

# Figure S2-S4 在 SI 末尾追加
# 找到末尾位置 (在 S4 supplementary methods 之后)
si.add_paragraph('')  # spacer

for fig_id in ['S2', 'S3', 'S4']:
    # 添加图
    p = si.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run()
    run.add_picture(str(si_fig_paths[fig_id]), width=Inches(6.5))
    # 添加 caption
    cap_para = si.add_paragraph(CAPTIONS[f'fig{fig_id}'])
    cap_para.runs[0].font.size = Pt(10)
    si.add_paragraph('')  # spacer
    print(f"  ✓ Figure {fig_id} added with caption")

si.save(str(SI_DOCX))
print(f"\n保存: {SI_DOCX}")

print("\n" + "="*80)
print("完成。备份: *.docx.fig_bak")
print("="*80)
print(f"\n图文件位置: {FIG_DIR}")
print("每张图独立文件夹, 内含 PNG + 各 panel CSV + README.txt")
